name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: CI
    uses: behm/reusable-workflows/.github/workflows/reusable-build.yml@add-reusable-workflow
    with:
      dotnet_version: 9.0.x